In [1]:
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import train_test_split

datafile = "test.csv"

def get_data(filename):
    df = pd.read_csv(filename)
    X_ = df[["Humidity","Visibility (km)"]]
    Y_ = df[["Temperature (C)"]]
    
    # Spliting data into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(X_, Y_, test_size=0.25, random_state=42)

   
    
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = get_data(datafile)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
# print(X_train,'\n', X_test, '\n', y_train, '\n', y_test)

def model(X, w, b):  
    """The linear regression model."""
    # write your code here
    return np.dot(X, w) + b

def squared_loss(y_hat, y):  #@save
    """Squared loss."""
    #write your code here for loss function
    return np.square(y_hat - y)

def create_model_parameter(mu, sigma, row, column):
    w = np.random.normal(mu, sigma, size=(row, column))
    w = np.transpose(w)
    w.reshape((2,1))
    b = 0
    return w,b

def gradient(loss,params):
    #compute gradeint of loss function with respect to params
    grads = (1/len(loss)) * np.sum(loss)
    return grads


# print(np.shape(np.array(np.transpose(np.mean(X_train, axis=0))).reshape((2,1))), np.shape(np.array(np.transpose(np.std(X_train))).reshape(2,1)))

w, b = create_model_parameter(np.mean(X_train, axis=0), np.std(X_train), 1, 2)
print(w,b)
y_hat = model(X_train, w, b)
print(y_hat)
result = squared_loss(y_hat, y_train)
print(result)





(7, 2) (3, 2) (7, 1) (3, 1)
[[0.83595533]
 [0.53329292]] 0
[[1.26822718]
 [1.07464185]
 [1.23942936]
 [0.93252944]
 [1.21806986]
 [1.21806986]
 [1.12479917]]
   Temperature (C)
0         0.554639
7         0.318092
2         0.470988
9         0.098506
4         0.491000
3         0.512832
6         0.395828


In [ ]:
b = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13, 17, 13]
u = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13, 17, 13]
def get_batch1(batchsiz, c):
    numNum = len(c)
    for i in range (0, numNum, batchsiz):
        yield c[i:min(i + batchsiz, numNum)]
def get_batch2(batchsiz, c):
    numNum = len(c)
    for i in range (0, numNum, batchsiz):
        yield c[i:min(i + batchsiz, numNum)]

for i in range(0, 10):
    batchesx = get_batch1(3, b)
    batchesy = get_batch2(3, u)
    print(batchesx, batchesy)
    for numx in batchesx:
        print(type(numx))
        print(numx, batchesy)
    batches = 0
    print("epoch over")

In [4]:
b = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13, 17, 13]
u = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13, 17, 13]
def get_batch(batchsiz, c, m):
    numNum = len(c)
    for i in range (0, numNum, batchsiz):
        yield c[i:min(i + batchsiz, numNum)], m[i:min(i + batchsiz, numNum)]
    return


for i in range(0, 10):
    batchesx = get_batch(3, b, u)
    print(batchesx)
    for numx, numy in batchesx:
        print(type(numx))
        print(numx, numy)
    print("epoch over", i)

<generator object get_batch at 0x0000021F71525770>
<class 'list'>
[0, 1, 2] [0, 1, 2]
<class 'list'>
[3, 4, 5] [3, 4, 5]
<class 'list'>
[6, 7, 8] [6, 7, 8]
<class 'list'>
[9, 10, 11] [9, 10, 11]
<class 'list'>
[12, 13, 17] [12, 13, 17]
<class 'list'>
[13] [13]
epoch over 0
<generator object get_batch at 0x0000021F714B1CB0>
<class 'list'>
[0, 1, 2] [0, 1, 2]
<class 'list'>
[3, 4, 5] [3, 4, 5]
<class 'list'>
[6, 7, 8] [6, 7, 8]
<class 'list'>
[9, 10, 11] [9, 10, 11]
<class 'list'>
[12, 13, 17] [12, 13, 17]
<class 'list'>
[13] [13]
epoch over 1
<generator object get_batch at 0x0000021F71525770>
<class 'list'>
[0, 1, 2] [0, 1, 2]
<class 'list'>
[3, 4, 5] [3, 4, 5]
<class 'list'>
[6, 7, 8] [6, 7, 8]
<class 'list'>
[9, 10, 11] [9, 10, 11]
<class 'list'>
[12, 13, 17] [12, 13, 17]
<class 'list'>
[13] [13]
epoch over 2
<generator object get_batch at 0x0000021F71524430>
<class 'list'>
[0, 1, 2] [0, 1, 2]
<class 'list'>
[3, 4, 5] [3, 4, 5]
<class 'list'>
[6, 7, 8] [6, 7, 8]
<class 'list'>
[9, 10,

In [8]:
a = np.array([[1, 0.95],
              [1, 0.85],
              [1, 0.80],
              [1, 0.70],
              [1, 0.60]])
aT = a.T
print(a)
print(aT)

[[1.   0.95]
 [1.   0.85]
 [1.   0.8 ]
 [1.   0.7 ]
 [1.   0.6 ]]
[[1.   1.   1.   1.   1.  ]
 [0.95 0.85 0.8  0.7  0.6 ]]


In [9]:
aTa = np.dot(aT, a)
print(aTa)

[[5.    3.9  ]
 [3.9   3.115]]


In [10]:
hTheta = np.array([0.85, 0.95, 0.70, 0.65, 0.70])
aThTheta = np.dot(aT, hTheta)
print(aThTheta)

[3.85 3.05]


In [15]:
calc = 3.115*(5.0/3.9)
print(calc)

3.993589743589744


In [16]:
calc2 = 3.9 - calc 
print(calc2)

-0.09358974358974415


In [18]:
calc3 = 3.85 - 3.05*(5.0/3.9)
print(calc3)

-0.060256410256410486


In [19]:
calc4 = calc3/calc2
print(calc4)

0.6438356164383549


In [21]:
calc5 = (3.05 - 3.115*(calc4))/3.9
print(calc5)

0.2678082191780831


In [22]:
b = np.array([[1, 0.65],
              [1, 0.75],
              [1, 0.77],
              [1, 0.83],
              [1, 0.87]])
Thetas = np.array([calc5, calc4])
print(b)
print(Thetas)

[[1.   0.65]
 [1.   0.75]
 [1.   0.77]
 [1.   0.83]
 [1.   0.87]]
[0.26780822 0.64383562]


In [23]:
pred = np.dot(b,Thetas)
print(pred)

[0.68630137 0.75068493 0.76356164 0.80219178 0.82794521]
