In [45]:
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import train_test_split

datafile = "test.csv"

def get_data(filename):
    df = pd.read_csv(filename)
    X_ = df[["Humidity","Visibility (km)"]]
    Y_ = df[["Temperature (C)"]]
    
    # Spliting data into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(X_, Y_, test_size=0.25, random_state=42)

   
    
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = get_data(datafile)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
print(X_train,'\n', X_test, '\n', y_train, '\n', y_test)

def model(X, w, b):  
    """The linear regression model."""
    # write your code here
    print(w,X)
    return np.dot(X, w) + b

def squared_loss(y_hat, y):  #@save
    """Squared loss."""
    #write your code here for loss function
    return np.square(y_hat - y)

def create_model_parameter(mu, sigma, row, column):
    w = np.random.normal(mu, sigma, size=(row, column))
    w = np.transpose(w)
    w.reshape((2,1))
    b = 0
    return w,b

def gradient(loss,params):
    #compute gradeint of loss function with respect to params
    grads = (1/len(loss)) * np.sum(loss)
    return grads


print(np.shape(np.array(np.transpose(np.mean(X_train, axis=0))).reshape((2,1))), np.shape(np.array(np.transpose(np.std(X_train))).reshape(2,1)))

w, b = create_model_parameter(np.mean(X_train, axis=0), np.std(X_train), 1, 2)
print(w,b)

y_hat = model(X_train, w, b)
print(y_hat)
result = squared_loss(y_hat, y_train)
print(result)





(7, 2) (3, 2) (7, 1) (3, 1)
   Humidity  Visibility (km)
0      0.89            0.983
7      0.89            0.620
2      0.89            0.929
9      0.72            0.620
4      0.83            0.983
3      0.83            0.983
6      0.95            0.620 
    Humidity  Visibility (km)
8      0.82            0.620
1      0.86            0.983
5      0.85            0.929 
    Temperature (C)
0         0.523486
7         0.510645
2         0.553144
9         0.618673
4         0.517356
3         0.501947
6         0.495651 
    Temperature (C)
8         0.574683
1         0.521084
5         0.519344
(2, 1) (2, 1)
(2, 1)
[[0.78598519]
 [1.10061064]] 0
[[0.78598519]
 [1.10061064]]    Humidity  Visibility (km)
0      0.89            0.983
7      0.89            0.620
2      0.89            0.929
9      0.72            0.620
4      0.83            0.983
3      0.83            0.983
6      0.95            0.620
[[1.78142708]
 [1.38190542]
 [1.72199411]
 [1.24828794]
 [1.73426797]
 [1.734